version: 2

jobs:
  noop:
    docker:
      - image: circleci/node:8.11
    steps:
      - run:
          name: noop
          command: 'echo Okay'
  deploy:
    docker:
      - image: circleci/node:8.11
    steps:
      - run:
          name: Install terraform
          working_directory: /tmp
          command: |
            curl -o terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
            unzip terraform.zip
            sudo mv terraform /usr/bin/terraform
            terraform -version

workflows:
  version: 2
  build_and_test:
    jobs:
      - noop