version: 2

jobs:
  install:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: install
          command: 'npm install'
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - packages/*/node_modules
  test:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: create mock config
          command: bin/task frontend:config --mock
      - run:
          name: test
          command: npm test
  build:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build
          command: npm run build
  deploy:
    docker:
      - image: circleci/node:8.11
    steps:
      - run:
          name: Install terraform
          working_directory: /tmp
          command: |
            curl -o terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
            unzip terraform.zip
            sudo mv terraform /usr/bin/terraform
            terraform -version

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install